### ISSUE TITLE
Veranstaltung öffnen/schließen

### ISSUE THREAD

**Issue by fmalcher** [hftlclub/club-monitor#1]
Funktion zum Freischalten/Deaktivieren des Frontends, damit es nur bei Veranstaltungen aktiv ist und am Ende der Party gesperrt werden kann.

**Comment by TilmannBach** [comment]
* ich denke das bezog sich noch maßgeblich auf den ursprungsverwendungszweck, den Karaoke Manager und ist daher ein Duplikat von #64 
* ist damit seit ceb3130665152e6cb9af12107fe70d70a75e14a5 implementiert

**Comment by fmalcher** [comment]
Macht schon auch für die Kurznachrichten und die Pizzabestellung Sinn. Das sollten wir dann aber - falls wir es jemals brauchen - pro Modul einzeln implementieren.
