### ISSUE TITLE
Fix scaling of infoscreen-slideshow on touchscreen-monitor

### ISSUE THREAD

**Issue by Chaosdelphin** [hftlclub/club-monitor#61]
Enable proper scaling of slide show on 1024x768 resolution 
(if there is no karaoke or spotifyable dj  available, the info-screen slideshow is displayed on this screen which looks actually very poor)

**Comment by Chaosdelphin** [comment]
...fix scaling on BOTH screens ;) (actually the big screen looks poor)

**Comment by TilmannBach** [comment]
you dont see this ticket as closed yet ;)

**Comment by TilmannBach** [comment]
fixed since 8f0a7cbb0d338de218b5afb03950f6e04c98a62b
